Enhance detection of patch files with better error messages
Instead of assuming that everything that doesn't look like a patch is an
EC, assume *.patch files are patches and error out with a clear message
why it was not detected as such.
Avoids confusing errors such as:
ERROR: Failed to process easyconfig foo.patch: Parsing easyconfig file failed: invalid syntax (<string>, line 1)